"use server";

import { revalidatePath } from "next/cache";
import { requireGrowth } from "@/lib/growth/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { generateProposalMarkdown } from "@/lib/growth/proposal";
import { sanitizeRecommendations } from "@/lib/growth/solutions";
import { NO_PROVIDER_MESSAGE } from "@/lib/ai/config";
import { dublinDate } from "@/lib/growth/dates";
import type { ResearchReport } from "@/lib/growth/research";

type Result = { ok?: boolean; error?: string } | undefined;

/**
 * Proposal Studio: drafts a proposal from everything the CRM holds on the
 * prospect (research, solutions, meeting notes and logged calls/meetings).
 * The draft is saved for editing — nothing goes to the prospect from here.
 */
export async function generateProposal(_prev: Result, formData: FormData): Promise<Result> {
  const { member } = await requireGrowth();
  const prospectId = String(formData.get("prospect_id") ?? "");
  if (!prospectId) return { error: "Missing prospect." };

  const admin = createAdminClient();
  const [{ data: prospect }, { data: research }, { data: meetings }, { data: callNotes }] =
    await Promise.all([
      admin.from("ge_prospects").select("*").eq("id", prospectId).maybeSingle(),
      admin
        .from("ge_research")
        .select("report, solutions")
        .eq("prospect_id", prospectId)
        .maybeSingle(),
      admin
        .from("ge_meetings")
        .select("scheduled_at, status, notes")
        .eq("prospect_id", prospectId)
        .order("scheduled_at", { ascending: false })
        .limit(5),
      admin
        .from("ge_activities")
        .select("content")
        .eq("prospect_id", prospectId)
        .in("type", ["call", "meeting", "note"])
        .order("created_at", { ascending: false })
        .limit(10),
    ]);
  if (!prospect) return { error: "Prospect not found." };

  const meetingNotes = [
    ...(meetings ?? [])
      .filter((m) => m.notes)
      .map((m) => `${m.status} meeting ${m.scheduled_at.slice(0, 10)}: ${m.notes}`),
    ...(callNotes ?? []).map((a) => a.content),
  ].slice(0, 12);

  let content: string;
  try {
    content = await generateProposalMarkdown(
      prospect,
      (research?.report as ResearchReport | undefined) ?? null,
      sanitizeRecommendations(research?.solutions),
      meetingNotes
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : "";
    if (message === "NO_PROVIDER") return { error: NO_PROVIDER_MESSAGE };
    return { error: "Proposal generation failed — try again in a moment." };
  }

  const { error } = await admin.from("ge_proposals").insert({
    prospect_id: prospectId,
    title: `AutomateIQ Proposal — ${prospect.company}`,
    content,
    created_by: member.id,
  });
  if (error) return { error: error.message };

  // Working on a proposal is a pipeline stage of its own — but never
  // regress a prospect whose proposal already went out (or who's closed).
  if (
    !["proposal_in_progress", "proposal_sent", "negotiation", "won", "lost",
      "do_not_contact", "archived"].includes(prospect.status)
  ) {
    await admin
      .from("ge_prospects")
      .update({ status: "proposal_in_progress" })
      .eq("id", prospectId);
  }

  await admin.from("ge_activities").insert({
    prospect_id: prospectId,
    type: "system",
    content: `Proposal draft generated by ${member.name}`,
    created_by: member.id,
  });

  revalidatePath(`/growth/prospects/${prospectId}`);
  return { ok: true };
}

export async function saveProposal(_prev: Result, formData: FormData): Promise<Result> {
  await requireGrowth();
  const id = String(formData.get("proposal_id") ?? "");
  const title = String(formData.get("title") ?? "").trim().slice(0, 300);
  const content = String(formData.get("content") ?? "").trim().slice(0, 60000);
  if (!id || !title || !content) return { error: "Title and content are required." };

  const admin = createAdminClient();
  const { data: proposal } = await admin
    .from("ge_proposals")
    .select("id, prospect_id")
    .eq("id", id)
    .maybeSingle();
  if (!proposal) return { error: "Proposal not found." };

  const { error } = await admin
    .from("ge_proposals")
    .update({ title, content })
    .eq("id", id);
  if (error) return { error: error.message };

  revalidatePath(`/growth/prospects/${proposal.prospect_id}`);
  return { ok: true };
}

/** Records that the (externally sent) proposal went out; stage → Proposal sent. */
export async function markProposalSent(_prev: Result, formData: FormData): Promise<Result> {
  const { member } = await requireGrowth();
  const id = String(formData.get("proposal_id") ?? "");
  if (!id) return { error: "Missing proposal." };

  const admin = createAdminClient();
  const { data: proposal } = await admin
    .from("ge_proposals")
    .select("id, prospect_id, status")
    .eq("id", id)
    .maybeSingle();
  if (!proposal) return { error: "Proposal not found." };

  const { error } = await admin
    .from("ge_proposals")
    .update({ status: "sent" })
    .eq("id", id);
  if (error) return { error: error.message };

  const { data: prospect } = await admin
    .from("ge_prospects")
    .select("status")
    .eq("id", proposal.prospect_id)
    .maybeSingle();
  if (
    prospect &&
    !["proposal_sent", "negotiation", "won", "lost", "do_not_contact", "archived"].includes(
      prospect.status
    )
  ) {
    await admin
      .from("ge_prospects")
      .update({
        status: "proposal_sent",
        // Chase the proposal if there's no word within a week.
        next_follow_up_at: dublinDate(7),
      })
      .eq("id", proposal.prospect_id);
  }

  await admin.from("ge_activities").insert({
    prospect_id: proposal.prospect_id,
    type: "status_change",
    content: `Proposal marked as sent by ${member.name} — follow-up scheduled in 7 days`,
    created_by: member.id,
  });

  revalidatePath(`/growth/prospects/${proposal.prospect_id}`);
  revalidatePath("/growth");
  return { ok: true };
}

export async function deleteProposal(_prev: Result, formData: FormData): Promise<Result> {
  await requireGrowth();
  const id = String(formData.get("proposal_id") ?? "");
  if (!id) return { error: "Missing proposal." };

  const admin = createAdminClient();
  const { data: proposal } = await admin
    .from("ge_proposals")
    .select("id, prospect_id, status")
    .eq("id", id)
    .maybeSingle();
  if (!proposal) return { error: "Proposal not found." };
  if (proposal.status === "sent") {
    return { error: "Sent proposals are part of the record — they can't be deleted." };
  }

  await admin.from("ge_proposals").delete().eq("id", id);
  revalidatePath(`/growth/prospects/${proposal.prospect_id}`);
  return { ok: true };
}
