import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import {
  encodeQuoteConfig,
  decodeQuoteConfig,
  quoteConfigSchema,
  type QuoteConfig,
} from "./quote-config";

/**
 * The quote widget's config encoding.
 *
 * This module was using `Buffer.from(json).toString("base64url")`, and
 * `encodeQuoteConfig` is called from builder.tsx — a "use client" component.
 * Node's Buffer knows the "base64url" encoding; the polyfill bundlers
 * substitute in the browser does not, so it threw
 *
 *     TypeError: Unknown encoding: base64url
 *
 * on hydration and took the whole /freetools/quote-builder page down. The tool
 * was completely unusable while the hub advertised it as working.
 *
 * Two things have to stay true forever:
 *
 *   1. It runs in a browser. No Buffer, no Node-only API.
 *   2. It produces and accepts EXACTLY what Buffer's base64url did — embed
 *      snippets already pasted into customers' own websites carry those
 *      strings, and /embed/quote has to keep reading them years from now.
 */

const cfg = (over: Partial<QuoteConfig> = {}): QuoteConfig =>
  quoteConfigSchema.parse({
    b: "Murphy Plumbing",
    s: [{ n: "Boiler service", p: 120 }],
    ...over,
  });

/** What the old implementation produced. The compatibility oracle. */
const bufferBase64Url = (o: unknown) =>
  Buffer.from(JSON.stringify(o)).toString("base64url");

describe("the encoding is browser-safe", () => {
  // Comments stripped: the file explains at length what it must NOT do, and a
  // naive text search would match the explanation rather than the code.
  const SRC = readFileSync(path.resolve(import.meta.dirname, "quote-config.ts"), "utf8")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/.*$/gm, "");

  it("never mentions Buffer — this file runs in the browser", () => {
    expect(SRC).not.toMatch(/\bBuffer\b/);
  });

  it("never asks for the base64url encoding by name", () => {
    // That string is what the polyfill choked on.
    expect(SRC).not.toMatch(/["']base64url["']/);
  });

  it("encodes multi-byte text, which btoa alone cannot", () => {
    expect(SRC).toContain("TextEncoder");
  });
});

describe("byte-for-byte compatible with what Buffer produced", () => {
  it.each([
    ["a typical config", cfg()],
    ["Irish names with fadas", cfg({ b: "Ó Briain Plumbing & Sons" })],
    ["emoji", cfg({ b: "Quick Fix 🔧" })],
    ["one-character name (padding case)", cfg({ b: "a" })],
    ["two-character name (padding case)", cfg({ b: "ab" })],
    ["three-character name (padding case)", cfg({ b: "abc" })],
  ])("%s", (_label, config) => {
    expect(encodeQuoteConfig(config)).toBe(bufferBase64Url(config));
  });

  it("still reads a string generated by the old Buffer code", () => {
    // The exact failure to avoid: a customer's live embed snippet going blank.
    const config = cfg({ b: "Ó Briain Plumbing" });
    const legacy = bufferBase64Url(config);
    expect(decodeQuoteConfig(legacy)).toEqual(config);
  });

  it("emits no padding and no URL-unsafe characters", () => {
    const encoded = encodeQuoteConfig(cfg({ b: "?".repeat(40) }));
    expect(encoded).not.toContain("=");
    expect(encoded).not.toContain("+");
    expect(encoded).not.toContain("/");
    expect(encoded).toMatch(/^[A-Za-z0-9_-]+$/);
  });
});

describe("round-trips", () => {
  it("survives a full encode/decode", () => {
    const config = cfg({ b: "Seán's Heating", note: "Prices ex VAT · Táillí" });
    expect(decodeQuoteConfig(encodeQuoteConfig(config))).toEqual(config);
  });

  it("returns null on rubbish instead of throwing", () => {
    // A public page renders this straight off a query param.
    for (const junk of ["", "!!!!", "a", "%%%%", "eyJub3QiOiJ2YWxpZCJ9"]) {
      expect(() => decodeQuoteConfig(junk)).not.toThrow();
      expect(decodeQuoteConfig(junk)).toBeNull();
    }
  });

  it("still refuses an oversized payload", () => {
    expect(decodeQuoteConfig("A".repeat(8001))).toBeNull();
  });
});
