"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  Sparkles,
  Send,
  CheckCheck,
  Copy,
  Check,
  Wand2,
  RefreshCw,
  Minimize2,
  Maximize2,
  BookmarkPlus,
  Save,
  Phone,
} from "lucide-react";
import {
  studioDraft,
  composeMessage,
  saveStudioTemplate,
} from "@/app/growth/(app)/inbox/actions";
import {
  CHANNELS,
  CHANNEL_META,
  PURPOSES,
  PURPOSE_META,
  TONES,
  type Channel,
  type MessagePurpose,
  type StudioTransform,
  type Tone,
} from "@/lib/growth/constants";

export type StudioDraftRow = {
  id: string;
  channel: Channel;
  purpose: MessagePurpose | null;
  subject: string | null;
  body: string;
};

type DraftState = { subject: string; body: string; messageId: string | null };
const emptyDraft: DraftState = { subject: "", body: "", messageId: null };
const key = (c: Channel, p: MessagePurpose) => `${c}:${p}`;

/**
 * The Message Studio: one tab per channel, five draft purposes, five tones,
 * AI generate + transform buttons — and a hard rule that nothing leaves the
 * screen except by the user copying it or explicitly pressing send/mark-sent.
 */
export function MessageStudio({
  prospectId,
  prospectEmail,
  prospectPhone = null,
  defaultChannel = "email",
  savedDrafts = [],
}: {
  prospectId: string;
  prospectEmail: string | null;
  prospectPhone?: string | null;
  defaultChannel?: Channel;
  /** Existing unsent drafts (e.g. auto-generated by research), newest first. */
  savedDrafts?: StudioDraftRow[];
}) {
  const router = useRouter();
  // Open on the most recent existing draft (savedDrafts is newest-first), so
  // "Review the drafted reply" / "Prep the follow-up" land straight on that
  // draft instead of an empty First-message tab that hides it behind the
  // channel/purpose dropdowns. Falls back to the default channel + first touch
  // when there are no drafts yet.
  const opener = savedDrafts[0];
  const [channel, setChannel] = useState<Channel>(opener?.channel ?? defaultChannel);
  const [purpose, setPurpose] = useState<MessagePurpose>(
    (opener?.purpose as MessagePurpose | null) ?? "first"
  );
  const [tone, setTone] = useState<Tone>("professional");
  // Drafts are kept per channel+purpose so switching tabs never loses work.
  const [drafts, setDrafts] = useState<Record<string, DraftState>>(() => {
    const initial: Record<string, DraftState> = {};
    for (const d of savedDrafts) {
      const p = d.purpose ?? "first";
      const k = key(d.channel, p as MessagePurpose);
      if (!initial[k]) {
        initial[k] = { subject: d.subject ?? "", body: d.body, messageId: d.id };
      }
    }
    return initial;
  });
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState<{ kind: "ok" | "error"; text: string } | null>(null);
  const [copied, setCopied] = useState(false);
  const [pending, startTransition] = useTransition();

  const active = drafts[key(channel, purpose)] ?? emptyDraft;
  const setActive = (next: Partial<DraftState>) =>
    setDrafts((prev) => ({
      ...prev,
      [key(channel, purpose)]: { ...(prev[key(channel, purpose)] ?? emptyDraft), ...next },
    }));

  async function generate(transform?: StudioTransform) {
    setNotice(null);
    setBusy(transform ?? "generate");
    // try/finally: a thrown server action (network blip, redeploy mid-session)
    // must never leave `busy` stuck — that freezes every studio button until
    // a full page reload.
    try {
      const result = await studioDraft({
        prospectId,
        channel,
        purpose,
        tone,
        currentText: transform ? active.body : undefined,
        transform,
      });
      if (!result.ok) {
        setNotice({ kind: "error", text: result.error });
        return;
      }
      setActive({ body: result.body, ...(result.subject ? { subject: result.subject } : {}) });
      setNotice({ kind: "ok", text: "Draft ready — review and edit before sending." });
    } catch {
      setNotice({
        kind: "error",
        text: "Connection hiccup — the draft didn't come back. Your text is untouched; try again.",
      });
    } finally {
      setBusy(null);
    }
  }

  function dispatch(mode: "draft" | "send_email" | "mark_sent") {
    setNotice(null);
    // An email that goes out (sent or recorded) needs a subject — a blank one
    // looks broken and hurts deliverability. Draft-saving stays unguarded.
    if (channel === "email" && mode !== "draft" && !active.subject.trim()) {
      setNotice({
        kind: "error",
        text: "Add a subject line first — an email with no subject looks broken and hurts deliverability.",
      });
      return;
    }
    startTransition(async () => {
      let result: Awaited<ReturnType<typeof composeMessage>>;
      try {
        result = await composeMessage({
          prospectId,
          channel,
          subject: channel === "email" ? active.subject : null,
          body: active.body,
          mode,
          purpose,
          tone,
          messageId: active.messageId ?? undefined,
        });
      } catch {
        // Thrown action (network blip) — nothing was confirmed sent; keep the
        // text so the user can simply press the button again.
        setNotice({
          kind: "error",
          text: "Connection hiccup — that didn't go through. Your draft is untouched; try again.",
        });
        return;
      }
      if (!result.ok) {
        setNotice({ kind: "error", text: result.error });
        return;
      }
      if (mode === "draft") {
        // Keep editing the same row — without capturing the new id, a second
        // save (or a later send) would create a duplicate draft.
        setActive({ messageId: result.messageId });
        setNotice({ kind: "ok", text: "Draft saved." });
      } else {
        setNotice({
          kind: "ok",
          text:
            mode === "send_email"
              ? "Email sent ✓ — prospect moved to Contacted, follow-up scheduled in 3 days."
              : channel === "call"
                ? "Call logged ✓ — prospect moved to Contacted, follow-up scheduled in 3 days."
                : "Recorded as sent ✓ — prospect moved to Contacted, follow-up scheduled in 3 days.",
        });
        setDrafts((prev) => ({ ...prev, [key(channel, purpose)]: emptyDraft }));
      }
      router.refresh();
    });
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(
        channel === "email" && active.subject
          ? `${active.subject}\n\n${active.body}`
          : active.body
      );
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      // Clipboard unavailable — no-op.
    }
  }

  const [phoneCopied, setPhoneCopied] = useState(false);
  async function handleCopyPhone() {
    if (!prospectPhone) return;
    try {
      await navigator.clipboard.writeText(prospectPhone);
      setPhoneCopied(true);
      setTimeout(() => setPhoneCopied(false), 1800);
    } catch {
      /* clipboard unavailable */
    }
  }

  async function handleSaveTemplate() {
    const name = window.prompt(
      "Template name:",
      `${CHANNEL_META[channel].label} — ${PURPOSE_META[purpose].label}`
    );
    if (!name) return;
    setNotice(null);
    try {
      const result = await saveStudioTemplate({
        name,
        channel,
        purpose,
        subject: channel === "email" ? active.subject : null,
        body: active.body,
      });
      setNotice(
        result.ok
          ? { kind: "ok", text: "Saved to templates (Settings → Templates)." }
          : { kind: "error", text: result.error }
      );
    } catch {
      setNotice({
        kind: "error",
        text: "Connection hiccup — the template didn't save. Try again.",
      });
    }
  }

  const anyBusy = busy !== null || pending;
  const hasText = active.body.trim().length > 0;

  const transformButtons: { mode: StudioTransform; label: string; icon: React.ReactNode }[] = [
    { mode: "improve", label: "Improve", icon: <Wand2 size={13} /> },
    { mode: "rewrite", label: "Rewrite", icon: <RefreshCw size={13} /> },
    { mode: "shorten", label: "Shorten", icon: <Minimize2 size={13} /> },
    { mode: "expand", label: "Expand", icon: <Maximize2 size={13} /> },
  ];

  return (
    <div>
      {/* Phone: tap to dial, one tap to copy — handy on the call channel. */}
      {prospectPhone && (
        <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginBottom: 10, fontSize: 13 }}>
          <a
            href={`tel:${prospectPhone.replace(/[^\d+]/g, "")}`}
            className="btn btn-secondary btn-sm"
            title="Tap to call"
          >
            <Phone size={13} /> {prospectPhone}
          </a>
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={handleCopyPhone}
            title="Copy the number"
          >
            {phoneCopied ? <Check size={13} style={{ color: "var(--green)" }} /> : <Copy size={13} />}
            {phoneCopied ? "Copied!" : "Copy number"}
          </button>
        </div>
      )}

      {/* Channel tabs */}
      <div role="tablist" aria-label="Channel" style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
        {CHANNELS.map((c) => (
          <button
            key={c}
            role="tab"
            aria-selected={channel === c}
            type="button"
            className={`btn btn-sm ${channel === c ? "btn-primary" : "btn-secondary"}`}
            onClick={() => {
              setChannel(c);
              // Land on a message type that actually HAS a draft for this
              // channel: the tab's • otherwise points at content hidden behind
              // the purpose dropdown (tap Instagram with a dot, see an empty
              // box because you were on Follow-up). Keeps the current purpose
              // whenever it already has text.
              if (!drafts[key(c, purpose)]?.body.trim()) {
                const withDraft = PURPOSES.find((p) => drafts[key(c, p)]?.body.trim());
                if (withDraft) setPurpose(withDraft);
              }
              setNotice(null);
            }}
          >
            {CHANNEL_META[c].label}
            {/* Live "draft in progress" dot: reads current state (which is
                seeded from savedDrafts) so it matches the message-type
                dropdown's dot — a draft you just generated shows immediately,
                and one you've sent/cleared stops showing, without a refresh. */}
            {Object.keys(drafts).some(
              (k) => k.startsWith(`${c}:`) && drafts[k].body.trim()
            )
              ? " •"
              : ""}
          </button>
        ))}
      </div>

      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginTop: 12 }}>
        <div style={{ flex: "1 1 200px" }}>
          <label htmlFor="ms-purpose" style={{ fontSize: 12, color: "var(--faint)" }}>
            Message type
          </label>
          <select
            id="ms-purpose"
            value={purpose}
            onChange={(e) => {
              // Clear the status line too (same as switching channel): a
              // "Draft saved"/"Email sent ✓" from the previous message type
              // must not linger over a different, often-empty draft.
              setPurpose(e.target.value as MessagePurpose);
              setNotice(null);
            }}
            style={{ width: "100%" }}
          >
            {PURPOSES.map((p) => (
              <option key={p} value={p}>
                {PURPOSE_META[p].label}
                {drafts[key(channel, p)]?.body ? " •" : ""}
              </option>
            ))}
          </select>
        </div>
        <div style={{ flex: "1 1 150px" }}>
          <label htmlFor="ms-tone" style={{ fontSize: 12, color: "var(--faint)" }}>
            Tone
          </label>
          <select
            id="ms-tone"
            value={tone}
            onChange={(e) => setTone(e.target.value as Tone)}
            style={{ width: "100%" }}
          >
            {TONES.map((t) => (
              <option key={t} value={t}>
                {t.charAt(0).toUpperCase() + t.slice(1)}
              </option>
            ))}
          </select>
        </div>
        <div style={{ alignSelf: "end" }}>
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => generate()}
            disabled={anyBusy}
          >
            <Sparkles size={14} />{" "}
            {busy === "generate" ? "Drafting…" : hasText ? "Regenerate" : "Generate draft"}
          </button>
        </div>
      </div>

      {channel === "email" && (
        <div style={{ marginTop: 12 }}>
          <label
            htmlFor="ms-subject"
            style={{ fontSize: 12, color: "var(--faint)", display: "flex", justifyContent: "space-between", gap: 8 }}
          >
            <span>Subject</span>
            {/* Inboxes cut a subject off around 78 chars; a subtle live hint
                keeps it tight (matches the inbox composer). */}
            {active.subject.length > 0 && (
              <span
                style={{
                  color: active.subject.length > 78 ? "var(--orange, #fb923c)" : "var(--faint)",
                }}
              >
                {active.subject.length}/78{active.subject.length > 78 ? " · may truncate in inboxes" : ""}
              </span>
            )}
          </label>
          <input
            id="ms-subject"
            value={active.subject}
            onChange={(e) => setActive({ subject: e.target.value })}
            maxLength={300}
            style={{ width: "100%" }}
          />
        </div>
      )}

      <div style={{ marginTop: 10 }}>
        <label htmlFor="ms-body" style={{ fontSize: 12, color: "var(--faint)" }}>
          Draft — nothing is ever sent without you
        </label>
        <textarea
          id="ms-body"
          value={active.body}
          onChange={(e) => setActive({ body: e.target.value })}
          rows={9}
          maxLength={10000}
          style={{ width: "100%" }}
          placeholder="Generate a draft from the research, or write your own…"
        />
      </div>

      {/* Transform row */}
      <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginTop: 8 }}>
        {transformButtons.map((t) => (
          <button
            key={t.mode}
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={() => generate(t.mode)}
            disabled={anyBusy || !hasText}
          >
            {t.icon} {busy === t.mode ? "Working…" : t.label}
          </button>
        ))}
        <button
          type="button"
          className="btn btn-secondary btn-sm"
          onClick={handleSaveTemplate}
          disabled={anyBusy || !hasText}
        >
          <BookmarkPlus size={13} /> Save template
        </button>
      </div>

      {notice && (
        <p
          role="status"
          style={{
            color: notice.kind === "ok" ? "var(--green, #34d399)" : "var(--red, #f87171)",
            fontSize: 13,
            margin: "10px 0 0",
          }}
        >
          {notice.text}
        </p>
      )}

      {/* Dispatch row */}
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12, alignItems: "center" }}>
        <button
          type="button"
          className="btn btn-secondary btn-sm"
          onClick={() => dispatch("draft")}
          disabled={anyBusy || !hasText}
        >
          <Save size={13} /> Save draft
        </button>
        <button
          type="button"
          className="btn btn-secondary btn-sm"
          onClick={handleCopy}
          disabled={!hasText}
        >
          {copied ? <Check size={13} style={{ color: "var(--green)" }} /> : <Copy size={13} />}
          {copied ? "Copied!" : channel === "call" ? "Copy script" : "Copy message"}
        </button>
        {channel === "email" ? (
          <button
            type="button"
            className="btn btn-primary btn-sm"
            onClick={() => dispatch("send_email")}
            disabled={anyBusy || !hasText || !prospectEmail}
            title={prospectEmail ? `Sends to ${prospectEmail}` : "No email on file"}
          >
            <Send size={13} /> {pending ? "Sending…" : "Send email now"}
          </button>
        ) : (
          <button
            type="button"
            className="btn btn-primary btn-sm"
            onClick={() => dispatch("mark_sent")}
            disabled={anyBusy || !hasText}
            title={
              channel === "call"
                ? "After you make the call, record it here"
                : `After you send it in ${CHANNEL_META[channel].label}, record it here`
            }
          >
            <CheckCheck size={13} /> {channel === "call" ? "Mark call made" : "Mark as sent"}
          </button>
        )}
      </div>
      <p style={{ fontSize: 12, color: "var(--faint)", marginTop: 8 }}>
        {channel === "email"
          ? "Send email now delivers through Resend and moves the prospect to Contacted with a follow-up in 3 days."
          : channel === "call"
            ? "Generate a call script (opener, why-them, the ask, objection responses, voicemail version), make the call yourself, then Mark call made — the CRM moves them to Contacted and schedules your follow-up."
            : `Copy the message, send it in ${CHANNEL_META[channel].label}, then Mark as sent — the CRM moves them to Contacted and schedules your follow-up automatically.`}
      </p>
    </div>
  );
}
